### ISSUE TITLE
dropdown 고장남

### ISSUE THREAD

**Issue by somewikiuser** [namu-theseed/theseed-skin-liberty#117]
작동 안함

**Comment by navyCarpet** [comment]
엔진에서 jQuery를 global화 시켜주어야 bootstrap이 작동하는데 최근 프론트엔드 업데이트때 global화 시키는 부분의 코드가 삭제되거나 변경된 것으로 예상됩니다. (관련 2de60fc)

**Comment by navyCarpet** [comment]
현재 liberty 스킨은 jQuery와 bootstrap script를 불러와 사용하고 있는데 사용처도 적고 스크립트 크기만 늘어나는 문제가 있습니다. 장기적으로 jQuery와 bootstrap script를 스킨에서 삭제할 필요가 있을 것 같습니다.

**Comment by somewikiuser** [comment]
고쳐졌습니다
