### ISSUE TITLE
리모컨 오류

### ISSUE THREAD

**Issue by RENAISSANCE-lll** [namu-theseed/theseed-skin-liberty#122]
https://www.alphawiki.org/w/알파위키

알파위키, 더시드위키에서 문서를 읽다가 리모컨을 클릭하면 무조건 대문으로 이동되어 리모컨이 작동하는 오류가 발생하고 있습니다.

**Comment by navyCarpet** [comment]
무슨 뜻인지 잘 모르겠습니다. 목차 버튼을 말씀하시는 거라면 SSR 오류로 보이며 이는 스킨 문제가 아니라 엔진 문제입니다. 현재 엔진이 불안정한 것으로 보이며 피드백 사이트에 문의해보세요

**Comment by RENAISSANCE-lll** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=namuwiki&no=89670

이러한 오류가 있었는데 지금 보니 해결된 모양입니다. 본 이슈는 닫겠습니다.
