### ISSUE TITLE
나무위키 리버티 스킨에서 설정이 눌러지지 않습니다.

### ISSUE THREAD

**Issue by LDY0225** [namu-theseed/theseed-skin-liberty#123]
나무위키 리버티 스킨에서 설정이 들어가지지 않습니다.(대략 한국시간으로 2024년 7월 25일 오후 10시 30분 확인)

그래서 현재 사이드바를 숨길 수 없으며 분류를 내릴 수도 없는 등 보기에 매우 불편합니다.

의도하신 게 아니고 제발 오류였으면 좋겠고 해결했으면 좋겠습니다.

**Comment by navyCarpet** [comment]
현재 수정되었습니다.
