### ISSUE TITLE
편집요청이 가능함에도 불구하고 버튼이 뜨지 않음

### ISSUE THREAD

**Issue by ghost** [namu-theseed/theseed-skin-liberty#133]
![Screenshot_20240920-225314_(1)](https://github.com/user-attachments/assets/f32d9274-89ac-4335-b01f-a085ea5f25fa)
알파위키의 사용자 이름공간을 보면 로그인된 사용자는 편집 요청이 가능한데 나무위키와 달리 편집 요청 버튼이 뜨지 않습니다.

**Comment by navyCarpet** [comment]
#132
