### ISSUE TITLE
휴대폰 환경에서 화살표 클릭시 박스가 왼쪽으로 짤림현상

### ISSUE THREAD

**Issue by AGPumBoy** [namu-theseed/theseed-skin-liberty#134]
휴대폰의 좌우너비가 좁으면 밑에 사진처럼 화살표 클릭시 왼쪽으로 박스가 열리는 것으로 판단되어 짤려서 보입니다.
버튼은 순서대로 먹히는데 왼쪽으로 스와이프 해도 그대로 짤린모습으로 나옵니다.

현재 스크린샷은 크롬의 개발자 도구를 사용 한 것이며 제 휴대폰인 S23 울트라에서도 동일증상이 나타납니다.
주로 휴대폰 좌우너비가 좁은 아이폰 계열에서 일어나고있습니다.

실험 결과(크롬 디바이스 선택기능 사용) : iPhone SE, iPhone 12 Pro, Samsung Galaxy S8+, Galaxy Z Fold 5

![image](https://github.com/user-attachments/assets/b2cd58cc-edf6-4480-b4da-a90dd2ccbfe7)

**Comment by navyCarpet** [comment]
content tool이 scroll 되는 방향으로 개선하도록 하겠습니다.

**Comment by AGPumBoy** [comment]
네 고맙습니다.
