### ISSUE TITLE
v4.25.2 업데이트 관련 문의

### ISSUE THREAD

**Issue by navyCarpet** [namu-theseed/theseed-skin-liberty#137]
@namu-theseed 
issue 확인을 잘 안하시는 걸로 알고 있지만 스킨 관련 문제가 있어 부득이하게 이슈 남깁니다.

1. 내부 데이터에선 rev uuid 데이터를 가지고 있는데 skin data로 넘겨줄 계획은 없는 것인가요? ($route.query로 확인하는 것보다 엔진 데이터의 신뢰가 높음)
2. 역사 페이지에서도 from, until을 사용하고 있는데 해당 부분도 uuid로 변경될 계획이 있나요?
3. rev selector의 개선 방향으로 from selector처럼 number input을 생각하고 있었는데 이전 리비전의 uuid를 불러올 방법은 따로 없는 것인가요?
4. 관련해서 스킨에 영향을 받는 경우 미리 공지를 받을 방법이 있었으면 좋겠습니다. 이때까진 namu님께서 직접 스킨을 수정해 주셔서 큰 문제 없었지만 전 나무위키 관리자가 아니라 관련 사항을 미리 알 수가 없습니다.

혹시 1번이 반영되어 skin data 수정 계획이 있으시다면 diff 페이지에 rev, oldrev(number type) data를 skin에도 넘겨주시면 감사하겠습니다. delete 페이지 viewName도 추가해 주시면 감사하겠습니다.

**Comment by namu-theseed** [comment]
1. 완료
2. 페이지네이션 키는 언제든지 다른 포맷으로 바뀔 수 있습니다. 다른 용도로는 사용을 안하는 것을 권장합니다.
3. 어떤 것이 필요한지 잘모르겠음
4. 더시드위키 계정 이름이 무엇인가요

**Comment by navyCarpet** [comment]
1. 확인했으나 ViewName_delete 부분에 문제가 있는 것으로 보입니다.
2. 그렇다면 혹시 from selector component를 엔진에서 지원해 주실 수 있나요? 해당 component 관련해서 반응은 꽤 긍정적인 것으로 보이고 역사 페이지 개선 전까진 실용성이 있어 보입니다.
3. 솔직하게 말하자면 좀 욕심이긴 하지만 난독화된 데이터에 접근하고 싶습니다.
4. navyCarpet으로 가입하였습니다.
