### ISSUE TITLE
'최근 변경' tab is over the '각주' popup so it covers the '각주' popup.

### ISSUE THREAD

**Issue by bicheondev** [namu-theseed/theseed-skin-liberty#26]
'최근 변경' 탭이 다음과 같이 '각주' 팝업 위에 있어서 '각주' 팝업을 가립니다:
'최근 변경' tab is over the '각주' popup so it covers the '각주' popup like this:
![image](https://user-images.githubusercontent.com/44262309/72659509-efc1f480-3a03-11ea-8a7d-cb840f425606.png)

**Comment by turbo-whistler** [comment]
CSS에서(파일명이 해시여서 어떤 CSS 문서인지는 이곳에 적지는 못하겠습니다) 다음 z-index를 삭제하면 해결되긴 하네요
```diff
.Liberty .content-wrapper .liberty-sidebar .liberty-right-fixed {
    position: fixed;
-   z-index: 999;
}
```
![image](https://user-images.githubusercontent.com/55873929/99946343-906a0900-2db9-11eb-9033-df0439618e2c.png)

**Comment by 2du** [comment]
수정했읍니다
