### ISSUE TITLE
오류 관련

### ISSUE THREAD

**Issue by Gwangtori** [namu-theseed/theseed-skin-liberty#34]
> * 사진 위치를 지정하지 않으면 중간이 아닌 위쪽으로 표시됩니다 [#](https://awiki.theseed.io/w/%ED%8C%8C%EC%9D%BC:0EC93181-5033-4FF9-8F14-583C8E0E566D.png)

> * 파일 업로드 할때 라이선스, 분류 선택 목록이 짤려서 나옵니다 [#](https://awiki.theseed.io/w/%ED%8C%8C%EC%9D%BC:%ED%99%94%EB%A9%B4%20%EC%BA%A1%EC%B2%98%202021-05-26%20205546.png)

**Comment by Gwangtori** [comment]
> * 사진 아래에 공백이 생김.
[https://awiki.theseed.io/w/%ED%8C%8C%EC%9D%BC:0EC93181-5033-4FF9-8F14-583C8E0E566D.png
](url)
> * 파일 업로드 할때 라이선스, 분류 선택 목록이 짤려서 나옴.
[https://awiki.theseed.io/w/%ED%8C%8C%EC%9D%BC:%ED%99%94%EB%A9%B4%20%EC%BA%A1%EC%B2%98%202021-05-26%20205546.png](url)

**Comment by Seohae1127** [comment]
설정을 켜면 상단바 때문에 다시 닫을 수 없는 오류도 있습니다.

**Comment by Tenpower** [comment]
#39 에서 해결됨
