### ISSUE TITLE
ACL Group

### ISSUE THREAD

**Issue by ghost** [namu-theseed/theseed-skin-liberty#35]
타 스킨과 다르게 ACL Group에서 메모가 길면 "삭제" 버튼이 보이지 않아 그룹 제거를 할 수 없습니다.
빠른 시내에 고쳐주시면 감사드리겠습니다.

![화면 캡처 2022-01-02 205029](https://user-images.githubusercontent.com/96424263/147874827-fdc9e1fe-50bd-4f40-b738-7b275eba1c81.png)

**Comment by Fakeness** [comment]
해결됨

**Comment by ontiger** [comment]
Maintainer, please close this issue.
