### ISSUE TITLE
모바일 UI 문제

### ISSUE THREAD

**Issue by OtneiV** [namu-theseed/theseed-skin-liberty#45]
![84C3FB5A-58F4-412E-9CC1-A641AF55A612](https://user-images.githubusercontent.com/109079203/203871472-097384ca-45a6-421c-afff-f3d65de07607.jpeg)

**Comment by Fakeness** [comment]
혹시 사용하시는 기기가 무엇인가요?

**Comment by Fakeness** [comment]
어떤 상황에 저렇게 되는지도 알려주시면 참고해 보겠습니다.

**Comment by Tenpower** [comment]
제 기기에선 문제가 없습니다

**Comment by Tenpower** [comment]
음 저렇게 하면 되나요?

**Comment by Gwangtori** [comment]
창 크기가 1023px 이하일 때 발생합니다. Windows와 iOS, 안드로이드 모두 발생하는 것을 보니 레이아웃에 타이틀이 위에 있어서 그런 것이 아닐까 싶어서 PR 넣었어요

**Comment by Fakeness** [comment]
title을 위로 가도록 의도한 것입니다.

**Comment by Fakeness** [comment]
@Gwangtori 창 크기를 1023px 이하로 해도 해당 증상이 확인되지 않습니다. 더 자세하게 말씀해 주시면 감사하겠습니다.

**Comment by Tenpower** [comment]
창크기 문제없다하고 윈도우 iOS 안드로이드 문제 없는걸로 봐선 브라우저쪽 문제가 예상이 됩니다

**Comment by Tenpower** [comment]
이슈 쓰신 분이 브라우저를 뭐 쓰는지 궁금한데 그걸 알 수가 없네요

**Comment by Fakeness** [comment]
@Gwangtori 님께서도 같은 증상이 일어나는 것 같은데 브라우저를 알려주시면 감사하겠습니다.

**Comment by Gwangtori** [comment]
1023px이 아니라 768px 였습니다. 죄송합니다.

3가지 환경 모두 크로미움 Edge로 테스트했으며, 쿠키와 캐시를 지워도 동일하게 발생합니다.

## iOS
![IMG_9910](https://user-images.githubusercontent.com/64156915/203909404-858a47eb-33ad-4154-bf49-b38c6b87b68e.png)

## Android
![Uploading Screenshots_2022-11-25-14-40-31.png…]()

**Comment by Tenpower** [comment]
- [ ] #49

**Comment by Fakeness** [comment]
@Tenpower 따로 해당 PR에 수정하진 않았으나 content-tools의 dropdown을 없애는 PR을 넣어 MARGE 되었으니 아마 위키에 적용되면 content-tools에는 해당 문제가 재현되진 않을 것입니다.

**Comment by Fakeness** [comment]
아무리 해도 해당 증상이 재현되지가 않네요...

**Comment by Tenpower** [comment]
저 역시 해당 증상을 모든 브라우저에서 적용한 결과 재현되지가 않습니다.

**Comment by Tenpower** [comment]
@Gwangtori @OtneiV Merge 되었네요 한번 확인 해보세요.

**Comment by Fakeness** [comment]
@Tenpower 아직 위키에는 반영되지 않았습니다.

**Comment by OtneiV** [comment]
그리고 기존에는 문서 제목이 아래쪽에 있지 않았나요? 업데이트 되면서 올라갔는데 오히려 더 불편해진거 같습니다.

**Comment by Tenpower** [comment]
- [ ] #50 

title? 말하는거면 아마 이거일 것 같네요.

**Comment by Fakeness** [comment]
모바일에서 title을 위로 올린 이유는 content-tools이 없는 다른 화면과 위치를 동일하게 만들기 위해 올린 것입니다.

**Comment by OtneiV** [comment]
업데이트된 스킨 적용된건가요?

**Comment by OtneiV** [comment]
오류 수정된 스킨 적용된건가요?

**Comment by Fakeness** [comment]
@OtneiV 나무위키에 리버티 스킨 적용해서 확인 부탁드립니다.

**Comment by OtneiV** [comment]
![1EE0D7F7-3BC1-4321-9D5F-2EB7AA9DB64C](https://user-images.githubusercontent.com/109079203/203939992-36d31ecf-456f-413b-9846-aa3a98de4b43.jpeg)

검색 부분에서는 동일한 문제가 발생합니다.

**Comment by Fakeness** [comment]
@OtneiV 제가 해당 증상 재현이 안되서 어떻게 해드릴 방법이 없습니다..

**Comment by OtneiV** [comment]
기존에는 저런 현상이 없었는데 검색 부분에서 바뀐 게 있나요?

**Comment by Tenpower** [comment]
![image](https://user-images.githubusercontent.com/94548284/203941740-10147b55-b9d1-4ae9-9b40-83b6ea78466f.png)

**Comment by sw5729** [comment]
문서 제목, UI에 들어간 글자를 제외한 글자의 크기가 너무 작은 것 같습니다. 글자 크기를 조금만 키워주시면 감사하겠습니다.

**Comment by Tenpower** [comment]
> 문서 제목, UI에 들어간 글자를 제외한 글자의 크기가 너무 작은 것 같습니다. 글자 크기를 조금만 키워주시면 감사하겠습니다.

이 주제는 다르므로 #53 여기서 얘기하면 될 듯 합니다.
