### ISSUE TITLE
사문 UI랑 문서제목 버그

### ISSUE THREAD

**Issue by Tenpower** [namu-theseed/theseed-skin-liberty#51]
![image](https://user-images.githubusercontent.com/94548284/203942375-aa625dbc-cdbe-4f6d-9169-0eea9bdc0957.png)

긴급적으로 이슈 오픈하고 수정되면 closed 하겠습니다.

**Comment by Fakeness** [comment]
PR 올렸습니다.

**Comment by Tenpower** [comment]
#52 에서 해결될듯

**Comment by Tenpower** [comment]
![image](https://user-images.githubusercontent.com/94548284/203943683-c6e65a68-c191-4174-9497-4338105a0ddd.png)
Fixed Closed Issue
