### ISSUE TITLE
문서 제목/UI를 제외한 글자가 너무 작음

### ISSUE THREAD

**Issue by Tenpower** [namu-theseed/theseed-skin-liberty#53]
문서 제목, UI에 들어간 글자를 제외한 글자의 크기가 너무 작은 것 같습니다. 글자 크기를 조금만 키워주시면 감사하겠습니다.

_Originally posted by @sw5729 in https://github.com/namu-theseed/theseed-skin-liberty/issues/45#issuecomment-1327204786_

**Comment by Tenpower** [comment]
@Fakeness @sw5729

**Comment by Fakeness** [comment]
#56

**Comment by Tenpower** [comment]
알겠습니다 #56 에서 해결된다네요.

**Comment by Tenpower** [comment]
@sw5729 이제 해결 되었나요?

**Comment by Tenpower** [comment]
https://www.alphawiki.org/diff/%EB%A6%AC%EB%B2%84%ED%8B%B0%20%EC%8A%A4%ED%82%A8?rev=64&oldrev=63

diff 내역을 보니까 해결 된 것 같네요 close합니다.
