### ISSUE TITLE
최근 바뀜 > 최근 변경

### ISSUE THREAD

**Issue by OtneiV** [namu-theseed/theseed-skin-liberty#54]
![304566D6-1E23-483D-A8CD-7598F862C1CB](https://user-images.githubusercontent.com/109079203/203947227-5077238c-f890-4a69-b9ac-25077af7c9c7.png)

위키 상단과 사이드바에 있는 최근 바뀜을 최근 변경으로 변경해주시면 감사드리겠습니다.

**Comment by Tenpower** [comment]
PR를 넣긴 넣었는데 구지 바꿀 필요가 있나 싶네요.

**Comment by OtneiV** [comment]
넣어주실 때 사이드바 부분도 같이 넣어주시면 감사드리겠습니다.

**Comment by Tenpower** [comment]
아 맞다 사이드바 혹시 이부분인가요?
![image](https://user-images.githubusercontent.com/94548284/203948612-54a68446-5f99-44d9-8f12-7afc069c920f.png)

**Comment by OtneiV** [comment]
네 그 부분 맞습니다.

**Comment by Tenpower** [comment]
저는 레이아웃쪽으로 다루고 있긴 하지만 저거 한번 찾아보겠습니다.

**Comment by Hoto-Cocoa** [comment]
굳이 바꿀 이유가 있을까요?

**Comment by Tenpower** [comment]
> 굳이 바꿀 이유가 있을까요?

솔직히 동의합니다. PR은 열었다만 closed하고 토론하는게 낫지 않을까요?
