### ISSUE TITLE
편집 요청 개선

### ISSUE THREAD

**Issue by Tenpower** [namu-theseed/theseed-skin-liberty#58]
![image](https://user-images.githubusercontent.com/94548284/203974583-d5a475db-df51-486b-98b5-4ee27a0b43f7.png)
![image](https://user-images.githubusercontent.com/94548284/203975068-8031e9af-5d73-4404-b5a6-1b3e25261243.png)

알파위키와 나무위키간의 비교 / "기준 판"과 "편집 요약"에 이어지는 text가 좀 아래쪽으로 치우쳤다고 생각이 듭니다.

**Comment by Fakeness** [comment]
#57

**Comment by Tenpower** [comment]
그럼 부탁드리겠습니다. 해결되면 close 할께요.
