### ISSUE TITLE
"토론 목록"추가 요청

### ISSUE THREAD

**Issue by Tenpower** [namu-theseed/theseed-skin-liberty#59]
![image](https://user-images.githubusercontent.com/94548284/203976883-8c6d9583-cec5-4cc4-8485-c3fa90775110.png)
이거를 더 시드 리버티에 구현이 가능할까요? 먼저 있는 title 개선이 merge되면 해야 될 것 같습니다.

**Comment by Fakeness** [comment]
#57

**Comment by Tenpower** [comment]
해결되면 close하겠습니다. 바로 넣으셨네요;
