### ISSUE TITLE
이미지 업로드할때 분류부분이 맨 밑에 부분에 가리네요.

### ISSUE THREAD

**Issue by Tenpower** [namu-theseed/theseed-skin-liberty#60]
![image](https://user-images.githubusercontent.com/94548284/204014914-1c40d846-0ab2-4f92-a96c-483aadb9945b.png)
업로드할려다가 우연히 발견함

**Comment by Fakeness** [comment]
이 부분은 인지하고 있으나 thread와 Search 페이지에 float: right; 속성인 버튼 때문에 고치기 어렵습니다.
알파위키 Upload 페이지에는 clear: both;가 적용되어 있는 것은 확인했습니다.

**Comment by Tenpower** [comment]
> 이 부분은 인지하고 있으나 thread와 Search 페이지에 float: right; 속성인 버튼 때문에 고치기 어렵습니다. 알파위키 Upload 페이지에는 clear: both;가 적용되어 있는 것은 확인했습니다.

음 그렇군요 일단 알겠습니다. 아까전에 올린 PR이 제대로 적용되었습니다.

**Comment by Fakeness** [comment]
> 이 부분은 인지하고 있으나 thread와 Search 페이지에 float: right; 속성인 버튼 때문에 고치기 어렵습니다. 알파위키 Upload 페이지에는 clear: both;가 적용되어 있는 것은 확인했습니다.

해당 부분 반영이 확인되어 #63 에서 반영될 예정입니다.
