### ISSUE TITLE
모바일에서 오른쪽 부분이 살짝 튀어나옴

### ISSUE THREAD

**Issue by Tenpower** [namu-theseed/theseed-skin-liberty#64]
![Screenshot_20221126-171142_Samsung Internet](https://user-images.githubusercontent.com/94548284/204079155-7d96baf0-710c-4693-9d37-c21d90027691.jpg)

여기만 수정하면 될 듯 하네요.

**Comment by Fakeness** [comment]
#63

**Comment by Tenpower** [comment]
#60 이랑 같이 해결 되면 닫기로 결정합니다.
