### ISSUE TITLE
지금 까지 진행된 theseed-skin-liberty 변경 및 계획

### ISSUE THREAD

**Issue by ghost** [namu-theseed/theseed-skin-liberty#65]
좀 더 보기 쉬우라고 이렇게나마 이슈 날립니다. 
저는 PR을 넣는 사람이 아니지만 그래도 작업이 진행되는 것을 실시간으로 체크하겠습니다.

- [ ] 설정 진행 사항
  - [x] 사이드바 고정 기능
  - [ ] 사이드바 비활성화 기능
  - [ ] 사이드바 왼쪽 기능
  - [ ] 내비게이션 바 컨트롤(사이트 맨위로/아래로 가는 것) 켜고 끄는 기능
  - [ ] 내비게이션 바 고정 기능
  - [x] 페이지 이동 시에 Search(검색) 창 초기화
- [ ] 기능 진행 사항
  - [ ] 모바일 최근 변경 나오게 구현
  - [x] 이전 버전 알림을 추가
  - [x] 토론 목록 기능 추가
  - [x] 문서 제목 클릭하여 문서로 나가기  
  - [x] 프로필 클릭하고 설정 밑에 "다크 테마로", "라이트 테마로" 기능
  - [x] 비로그인시에 "Please login!" 로그인시에 "Member"로 표시하는 기능
- [ ] 수정 진행 사항
  - [x] 이미지 업로드 할 때 분류부분이 가려짐
  - [x] 모바일 부분에서 로그인 클릭시 살짝 튀어나옴
  - [x] 최근 바뀜을 최근 변경으로 업로드를 파일 올리기로 수정
  - [x] ACL Group을 들어갈때 삭제 버튼이 안 나오는 것
  - [x] 분류가 되지 않은 문서가 없는 것
  - [ ] 도구 안에 아이콘 넣기

**Comment by Tenpower** [comment]
사이드바 고정 기능 : #63

**Comment by Tenpower** [comment]
계속 요구를 하는 것 같아 너무 죄송합니다. 버그 수정도 수정이지만 구현 해야 할 설정도 있는 것 같아서 넣습니다.

**Comment by Tenpower** [comment]
not planned로 변경 - 스킨의 최종본이 공개됨에 따라 닫습니다.

**Comment by Fakeness** [comment]
저는 더 이상 수정하지 않을 생각이지만, 다른 분께서 PR을 또 넣을 수 있으니 열어두시는 것도 나쁘지 않을 것 같네요

**Comment by Tenpower** [comment]
다시 열어두었습니다 현재 진행되었던 것들 싹 다 기록 해놓겠습니다. 그동안 감사했습니다! buma는 아마 나중에 고쳐주시길...

**Comment by Tenpower** [comment]
- [ ] #68
