### ISSUE TITLE
도구 아이콘 적용 문의

### ISSUE THREAD

**Issue by OtneiV** [namu-theseed/theseed-skin-liberty#68]
![image](https://user-images.githubusercontent.com/109079203/204133863-6c9dd363-4abd-48cf-8c44-b100533724ea.png)

위와 같이 도구를 펼치면 도구 아이콘과 함께 떴으면 좋겠습니다.

**Comment by Tenpower** [comment]
아이콘을 찾았습니다. 오늘 내일중에 PR넣겠습니다.

**Comment by Tenpower** [comment]
#69
