### ISSUE TITLE
모바일에서 오른쪽으로 살짝 튀어나온 도구 탭

### ISSUE THREAD

**Issue by OtneiV** [namu-theseed/theseed-skin-liberty#70]
![B7BDE463-2D69-40F8-9CBF-CB7217C6F09C](https://user-images.githubusercontent.com/109079203/204140774-bf5191de-8328-4d78-8552-665cf9bf00ec.jpeg)

**Comment by Tenpower** [comment]
@OtneiV 군복무중이라 그런데 해결이 된건가요?
