### ISSUE TITLE
불-편

### ISSUE THREAD

**Issue by nawega** [namu-theseed/theseed-skin-liberty#84]
<img width="232" alt="image" src="https://github.com/namu-theseed/theseed-skin-liberty/assets/104440972/606d7e55-b3dd-471e-ad16-abd0dfb7ace7">
theseed.io nawega 계정 로그인 후 촬영. Windows 11, Chrome 시크릿 모드.

**Comment by nawega** [comment]
기기에 따라 height가 달라지는듯

**Comment by theseeduser** [comment]
https://github.com/namu-theseed/theseed-skin-liberty/pull/96
